/**
 * 100 variants per proactive-message category. Picked at send time by
 * pickFreshVariant in sean-messages.ts, which excludes any variant a
 * given client has received in the last 365 days.
 *
 * Sizing math:
 *   - Cooldown: 48 hours per category → max ~182 fires per category per year
 *   - Bank size: 100 variants per category
 *   - For most clients (occasional misses, weekly rhythms) the year never
 *     repeats. For the rare client who maxes out behavioral_24h every
 *     other day for a full year, repeats begin around month 6-7 — and
 *     even then we deduplicate against what's been sent, so the freshest
 *     unseen variant is always picked first.
 *
 * Sean wrote most of these directly — see commit history. The remaining
 * 150 (Fri 51-100, 24h 51-100, 72h 51-100) were drafted to match his
 * tone: short, conversational, mostly questions, no "sis/girl/baby,"
 * sparing use of signature phrases.
 *
 * Edit these directly. The file is plain TypeScript string arrays — no
 * tooling, no schema, no DB migration to change a line.
 */

/* ────────────────────────────────────────────────────────────── *
 * Push notification title pools — picked independently of the body
 * so the lockscreen line varies even within the same category.
 * ────────────────────────────────────────────────────────────── */

export const RHYTHM_WED_PM_TITLES: string[] = [
  "Mid-week check from Sean",
  "Halfway. Where you at?",
  "Wednesday night",
  "Mid-week pulse",
  "Three days in",
  "Sean: mid-week check",
  "Wednesday night, Sean",
  "Halfway through",
  "Mid-week from Sean",
  "Sean checking in",
];

export const RHYTHM_FRI_PM_TITLES: string[] = [
  "Weekend incoming",
  "Friday from Sean",
  "Tomorrow's Saturday",
  "Pre-weekend check",
  "Sean: weekend plan",
  "Friday night",
  "Weekend warning",
  "Heads up — Saturday",
  "Pre-Saturday from Sean",
  "Friday night plan",
];

export const BEHAVIORAL_24H_TITLES: string[] = [
  "Sean noticed",
  "Checking in",
  "Hey, where you at?",
  "Sean checking in",
  "Quick check",
  "Sean's noticed",
  "Talk to me",
  "Empty day",
  "Sean reaching out",
  "Quiet day from Sean",
];

export const BEHAVIORAL_72H_TITLES: string[] = [
  "Three days, Sean checking in",
  "Three days quiet",
  "Talk to me",
  "Sean reaching out",
  "Where you at?",
  "Three days — Sean",
  "Sean asking",
  "Quiet stretch — Sean here",
  "Door's still open",
  "Sean after 3 days",
];

export const PROGRESS_STREAK_3_TITLES: string[] = [
  "3 days locked in",
  "Sean: 3-day streak",
  "Three straight",
  "3 days",
  "Pattern's forming",
  "Sean noticed: 3 days",
  "Three days locked",
];

export const PROGRESS_STREAK_5_TITLES: string[] = [
  "5-day streak",
  "Sean: five days",
  "Five straight",
  "5 days locked",
  "Sean noticed: 5 days",
  "Five days in",
  "Sean: 5 days",
];

export const PROGRESS_STREAK_7_TITLES: string[] = [
  "7 days. Locked in.",
  "Sean: one full week",
  "7-day streak",
  "Seven straight",
  "Full week",
  "Sean noticed: 7 days",
  "Sean: full week",
];

export const PROGRESS_STREAK_14_TITLES: string[] = [
  "14 days locked in",
  "Sean: two-week streak",
  "Two full weeks",
  "14 days",
  "Sean noticed: two weeks",
  "14-day streak",
  "Two weeks in",
];

export const PROGRESS_STREAK_30_TITLES: string[] = [
  "30 days. A full month.",
  "Sean: one-month streak",
  "One full month",
  "30 days locked in",
  "Sean noticed: 30 days",
  "30-day streak",
  "A month in",
];

export const PROGRESS_STREAK_60_TITLES: string[] = [
  "60 days. Two months.",
  "Sean: two-month streak",
  "Two months locked in",
  "60 days",
  "Sean noticed: 60 days",
  "60-day streak",
  "Two months in",
];

export const PROGRESS_STREAK_90_TITLES: string[] = [
  "90 days. Three months.",
  "Sean: three-month streak",
  "Three months locked",
  "90 days",
  "Sean noticed: 90 days",
  "90-day streak",
  "A full quarter",
];

/* ────────────────────────────────────────────────────────────── *
 * RHYTHM — WEDNESDAY 7 PM
 * Midweek reflection / honest check-in.
 * ────────────────────────────────────────────────────────────── */

export const RHYTHM_WED_PM_VARIANTS: string[] = [
  `Wednesday night. Half the week's already gone — how you really feeling?`,
  `Midweek check-in. No fake answers tonight.`,
  `Wednesday PM. Pause for a second and be honest with yourself.`,
  `Halfway through the week already. You holding up?`,
  `Wednesday evenings always make people reflect a little deeper.`,
  `Before you log tonight… how's your mind actually doing?`,
  `Midweek honesty hour.`,
  `Wednesday night energy check.`,
  `The week's moving fast. Don't forget to check in with yourself too.`,
  `Halfway there. Mentally, emotionally, physically… where you at?`,
  `Wednesday PM thoughts.`,
  `Be real tonight: are you okay or just staying busy?`,
  `Midweek can feel heavier than people admit.`,
  `Wednesday night reminder to slow down for a second.`,
  `How's your spirit feeling this week?`,
  `Midway through the grind. Don't lose yourself in it.`,
  `Some weeks hit harder by Wednesday night.`,
  `Before tomorrow starts, ask yourself what you really need.`,
  `Wednesday evening gut check.`,
  `Half the week gone already. Crazy.`,
  `Midweek reflection. What's been weighing on you?`,
  `Wednesday nights expose what we've been avoiding all week.`,
  `Quick check-in before the night disappears.`,
  `Be honest with yourself tonight. That's all.`,
  `Midweek reminder that burnout can look productive.`,
  `Wednesday PM. Deep breath.`,
  `The middle of the week tends to reveal your real energy.`,
  `Halfway through the week — surviving or thriving?`,
  `Wednesday nights always feel a little reflective.`,
  `Don't just ask if you're busy. Ask if you're okay.`,
  `Midweek pause.`,
  `Wednesday evening. What's your mental looking like?`,
  `Some of y'all been carrying too much quietly this week.`,
  `Halfway through already. You proud of how you've handled it?`,
  `Wednesday PM reminder to stop ignoring yourself.`,
  `Another Wednesday night. Another chance to reset mentally.`,
  `Midweek check-in for the people running on fumes.`,
  `Tonight feels like one of those "sit and think" nights.`,
  `Wednesday evenings hit different after a long week.`,
  `The week keeps moving whether we process it or not.`,
  `Halfway through the week. How's life feeling lately?`,
  `Midweek honesty feels better than fake positivity.`,
  `Wednesday PM. What's actually on your mind tonight?`,
  `Pause before bed tonight and check in with yourself.`,
  `Wednesday night reflection > pretending everything's fine.`,
  `Midweek reality check.`,
  `Half the week done. Still aligned with yourself?`,
  `Wednesdays always seem to bring the truth out.`,
  `Don't ignore what your body and mind are trying to tell you tonight.`,
  `Midweek self-awareness matters more than motivation.`,
  `Wednesday evening reminder that rest is productive too.`,
  `Another Wednesday. Another reminder to breathe.`,
  `Halfway through the week and somehow already exhausted.`,
  `Midweek can make people feel weirdly emotional.`,
  `Wednesday PM. Quiet moment with yourself.`,
  `Before the night ends, be honest about what's draining you.`,
  `Midweek reflection without judgment.`,
  `Wednesday night. How are you *really*?`,
  `The middle of the week can sneak up on your mental.`,
  `Halfway there. Keep going.`,
  `Wednesday PM energy check.`,
  `Some of y'all need peace more than pressure tonight.`,
  `Midweek reminder to stop pouring from an empty cup.`,
  `Wednesday nights always feel like a mirror.`,
  `Half the week's gone. What's your energy saying?`,
  `Midweek pause before life speeds back up tomorrow.`,
  `Wednesday evening thoughts getting loud tonight?`,
  `Be truthful with yourself tonight, even if it's uncomfortable.`,
  `Midweek reminder that you're human before anything else.`,
  `Wednesday PM. No filters. How are you?`,
  `Halfway through the week and still pushing.`,
  `Wednesday night reflection starts with honesty.`,
  `Midweek check-in because nobody asks enough.`,
  `Another Wednesday evening. You still with yourself mentally?`,
  `Before you scroll all night, pause for a second.`,
  `Wednesdays reveal what we've been suppressing.`,
  `Midweek reminder that consistency includes checking on yourself too.`,
  `Wednesday PM. Sit with your thoughts for a minute.`,
  `Half the week done. What's been the hardest part?`,
  `Wednesday night. Don't ignore your mental tonight.`,
  `Midweek can either sharpen you or drain you.`,
  `Wednesday evening reminder to listen to yourself.`,
  `Some weeks feel long by Wednesday night.`,
  `Halfway through. You still moving with intention?`,
  `Midweek reflection can change your whole week.`,
  `Wednesday PM. Let yourself slow down tonight.`,
  `Another Wednesday night in the books almost.`,
  `Midweek reminder to stop pretending you're not tired.`,
  `Wednesday evenings are underrated for self-reflection.`,
  `Halfway through the week and still figuring it out.`,
  `Midweek thoughts. Honest thoughts.`,
  `Wednesday night check-in for the overthinkers.`,
  `Pause tonight. How's your heart doing lately?`,
  `Midweek reminder that you don't have to fake "good."`,
  `Wednesday PM. You carrying stress you haven't acknowledged?`,
  `Halfway there. Give yourself some grace tonight.`,
  `Wednesday evenings always expose your real mood.`,
  `Midweek. Be kind to yourself, but honest too.`,
  `Wednesday night. What do you need right now?`,
  `Another midweek moment. Another chance to check in with yourself.`,
];

/* ────────────────────────────────────────────────────────────── *
 * RHYTHM — FRIDAY 7 PM
 * Weekend discipline / don't undo progress.
 * ────────────────────────────────────────────────────────────── */

export const RHYTHM_FRI_PM_VARIANTS: string[] = [
  `Friday night. You already know weekends test people.`,
  `Tomorrow's Saturday. Don't let two days erase five.`,
  `Have fun this weekend — just don't disappear completely.`,
  `Enjoy yourself. Just remember your goals didn't clock out.`,
  `Friday PM reminder: moderation still matters.`,
  `The weekend isn't the problem. Going overboard is.`,
  `Tomorrow tends to expose discipline real quick.`,
  `Have your fun. Hit your protein. Stay somewhat locked in.`,
  `Friday night check-in before the weekend chaos starts.`,
  `Don't spend all week building momentum just to abandon it Saturday.`,
  `Weekends count too.`,
  `Enjoy the food. Just don't lose control with it.`,
  `Friday PM. Keep at least one promise to yourself this weekend.`,
  `The goal isn't perfection — just don't completely fold.`,
  `Saturday habits usually reveal the truth.`,
  `Weekend reminder: consistency matters more than intensity.`,
  `Have fun, but remember who you said you wanted to become.`,
  `Friday night discipline hits different.`,
  `Don't let "I deserve it" turn into self-sabotage.`,
  `Tomorrow is where routines usually fall apart.`,
  `A weekend off track can easily become a week off track.`,
  `Friday PM reminder not to negotiate with your goals all weekend.`,
  `You can enjoy life without undoing your progress.`,
  `Weekends are where habits either survive or collapse.`,
  `Have your meals. Hit your protein. Keep moving.`,
  `Friday night. Don't black out your discipline.`,
  `Saturday temptation loading…`,
  `You don't need to be perfect this weekend. Just intentional.`,
  `Enjoy the weekend without abandoning yourself.`,
  `Friday PM reality check.`,
  `Don't let one weekend become another reset Monday.`,
  `Most people lose momentum on the weekends. Don't be most people.`,
  `You can celebrate and still stay aligned.`,
  `Friday night reminder to stay somewhat accountable.`,
  `The weekend's coming. Stay aware.`,
  `Don't undo the week chasing temporary comfort.`,
  `Saturday doesn't have to mean self-destruction.`,
  `Keep your standards with you this weekend.`,
  `Friday PM. Stay grounded.`,
  `A little discipline now saves regret later.`,
  `Weekends reveal who's actually committed.`,
  `Enjoy yourself without disappearing from your goals.`,
  `Friday night. Keep at least some structure.`,
  `Don't spend Monday trying to recover from Saturday.`,
  `Have fun this weekend — just stay conscious.`,
  `Friday PM reminder that balance is real discipline.`,
  `Tomorrow can either maintain momentum or kill it.`,
  `One meal won't ruin you. One mindset might.`,
  `Weekends are easier when you stay intentional early.`,
  `Friday night check-in before the excuses start.`,
  `Friday PM. Weekends are made for people who stay grounded.`,
  `Saturday energy starts tonight. Wind down properly.`,
  `Friday night reminder: rest counts too.`,
  `Tomorrow's a test, not a vacation.`,
  `Don't drift this weekend. Stay close to yourself.`,
  `Friday PM. Keep your standards intact this weekend.`,
  `The weekend will only undo you if you let it.`,
  `Stay aligned. Even when nobody's holding you accountable.`,
  `Friday night. Don't punish yourself with food this weekend.`,
  `Weekends test discipline more than weekdays.`,
  `You can enjoy the moment without ditching the goal.`,
  `Friday PM. Be intentional, not perfect.`,
  `The hardest discipline is when nobody's watching.`,
  `Have the meal. Just have the truth too.`,
  `Friday night. Your goals don't pause for two days.`,
  `Saturday tests your real commitment.`,
  `Weekends are usually where avoidance shows up.`,
  `Friday PM. Stay in tune with your body this weekend.`,
  `Don't enter Saturday already running from yourself.`,
  `Tomorrow's discipline starts with tonight's decisions.`,
  `Friday night. The weekend can either build you or expose you.`,
  `Stay close to your why this weekend.`,
  `Don't make the weekend an excuse to stop showing up.`,
  `Friday PM. Be honest about what tomorrow usually looks like.`,
  `Discipline doesn't take vacations.`,
  `Saturday morning will tell you exactly how Friday night went.`,
  `Friday night reminder that boundaries are part of self-respect.`,
  `The weekend is just two more days to be on purpose.`,
  `Don't get loud with the food just because it's Friday.`,
  `Friday PM. Stay grounded. Stay yourself.`,
  `The weekend's where good intentions go to die — keep yours alive.`,
  `Tomorrow doesn't have to break you. You choose.`,
  `Friday night check before the noise begins.`,
  `Stay connected to your goals this weekend.`,
  `Don't let the weekend pull you away from your real self.`,
  `Friday PM. Pace yourself through tomorrow.`,
  `Saturday's been the day you usually lose ground. Change the pattern.`,
  `Don't make food the focus of your weekend. Make peace the focus.`,
  `Friday night. Keep your standards quietly intact.`,
  `The weekend's not a free pass to disrespect yourself.`,
  `Saturday is the day discipline becomes a personality, not a phase.`,
  `Friday PM. Stay tied to the version of you that's been showing up.`,
  `The weekend doesn't get to undo your week.`,
  `Don't carry guilt into Monday. Carry awareness into Saturday.`,
  `Friday night. Stay sharp tomorrow.`,
  `Saturday's where slow growth either continues or stalls.`,
  `Don't ghost your progress this weekend.`,
  `Friday PM. Hold your line. Quietly.`,
  `The weekend's just two more chances to choose yourself.`,
  `Friday night. Stay intentional. Stay home in yourself.`,
];

/* ────────────────────────────────────────────────────────────── *
 * BEHAVIORAL — NO LOG IN 24 HOURS
 * Gentle accountability. Concern + open door + small next step.
 * ────────────────────────────────────────────────────────────── */

export const BEHAVIORAL_24H_VARIANTS: string[] = [
  `Didn't see you today. Everything good?`,
  `You disappeared a little today. Talk to me.`,
  `No log today. We getting back on track tomorrow?`,
  `One off day doesn't have to become a spiral.`,
  `Didn't hear from you today. Don't drift too far.`,
  `Missing a day happens. Staying gone is the problem.`,
  `Just checking in — you good?`,
  `No shame. Just don't vanish completely.`,
  `Didn't see you log today. What happened?`,
  `Off days are normal. Isolation isn't.`,
  `You don't have to disappear because the day wasn't perfect.`,
  `Didn't see activity from you today. Let's regroup.`,
  `One rough day doesn't erase your progress.`,
  `Everything okay on your end?`,
  `Today got away from you?`,
  `Missing one day isn't failure. Giving up is.`,
  `Didn't see you in here today. Still with me?`,
  `Don't avoid the process when things feel hard.`,
  `A missed day is easier to recover from than a missed week.`,
  `No log today. Let's not let that become a habit.`,
  `Just because today slipped doesn't mean tomorrow has to.`,
  `Checking in because consistency matters.`,
  `You don't need perfection to keep going.`,
  `Didn't see you today. We resetting tomorrow?`,
  `Hard days are usually when accountability matters most.`,
  `One missed check-in isn't the end.`,
  `Don't ghost yourself when life gets messy.`,
  `No activity today. Be honest — what's going on?`,
  `You usually feel worse staying away longer.`,
  `Missing a day happens to everybody.`,
  `Progress doesn't disappear overnight.`,
  `Today wasn't ideal. That's okay. Tomorrow still exists.`,
  `Didn't see you in here. You alright mentally?`,
  `Some days are survival mode days. Just don't quit.`,
  `Accountability gets hardest right before it matters most.`,
  `Don't disappear on yourself now.`,
  `You don't need motivation to check in.`,
  `One missed day can still become a comeback.`,
  `Didn't hear from you today. Let's lock back in soon.`,
  `A rough day doesn't cancel your goals.`,
  `Missing today doesn't mean you failed.`,
  `We all slip. Just don't stay down there.`,
  `Didn't see you today. You coming back tomorrow?`,
  `Momentum is easier to maintain than rebuild.`,
  `Some people disappear when progress slows. Don't do that.`,
  `The hard days are part of the process too.`,
  `You don't have to earn your way back in here.`,
  `No log today. No judgment either.`,
  `Just checking in before another day passes.`,
  `One day off track doesn't define you.`,
  `No log today. Don't carry the silence into another day.`,
  `Quiet day. The work doesn't shame you — but it's still waiting.`,
  `Today went quiet. Don't disappear from the version of you doing this.`,
  `Empty entry. Real talk: was it busy or was it heavy?`,
  `No log today. Show up tomorrow even if tonight feels off.`,
  `Today silent. The journey is still yours when you come back.`,
  `Empty day. Stop tonight. Drink water. Eat protein. Reset.`,
  `Quiet 24. Don't isolate when things get hard.`,
  `No log. Tomorrow morning, walk first. The rest follows.`,
  `Empty entry. The body doesn't care that today was rough.`,
  `Today silent. Even a rough day is part of the data.`,
  `No log. Don't let one quiet day kill momentum.`,
  `Quiet day. Honest check: are you tired or are you hiding?`,
  `Empty 24. The work doesn't punish slips. It rewards returns.`,
  `No log today. Be gentle but be honest.`,
  `Today went quiet. Show up tomorrow with intention.`,
  `Empty day. The work waits, but momentum doesn't.`,
  `No log today. Don't bury the silence — break it.`,
  `Quiet check. Real answer: did you eat or did you avoid the log?`,
  `Empty entry. Tomorrow's a reset. Use it.`,
  `No log today. The hardest meal to log is the one after a missed day. Log it anyway.`,
  `Today silent. Eat protein tonight. Even a shake counts.`,
  `Quiet day. Show me you can come back fast.`,
  `No log. We adjust. We don't quit. Big difference.`,
  `Empty 24. Don't make today's silence tomorrow's pattern.`,
  `Today quiet. The road back is always one entry away.`,
  `No log today. Pull yourself together. One small meal. Logged. Done.`,
  `Empty entry. Don't let today's avoidance build into a streak of silence.`,
  `Quiet day. Stop the slide tonight if you can.`,
  `No log today. Eat with intention before bed.`,
  `Today went silent. Don't let it speak for who you are.`,
  `Empty day on the log. Just show up tomorrow. That's the whole ask.`,
  `No log. Want me to make it simple? Three meals tomorrow. Three logs. Done.`,
  `Quiet day. The journey doesn't punish absence. It celebrates return.`,
  `Empty entry. Honest check: are you hiding from food or hiding from feelings?`,
  `No log today. The work is still yours. Pick it back up.`,
  `Today silent. The version of you with goals is still here. Listen for her.`,
  `Empty day. Don't carry guilt. Just carry intent.`,
  `No log. The small step tomorrow is logging breakfast. Start there.`,
  `Quiet 24. Tomorrow's a clean slate. Don't waste it.`,
  `Empty entry today. Stop. Reset. Tomorrow we move.`,
  `No log today. Don't quit on yourself quietly.`,
  `Today silent. The work keeps going whether you show up or not. Show up.`,
  `Quiet day. Honest check: what part of today made the log feel impossible?`,
  `No log. The body needs the work. So does the head.`,
  `Empty entry. Pull yourself out of the quiet. Tomorrow.`,
  `Today silent. Don't disappear because today felt heavy.`,
  `No log today. The road back is short. Walk it tomorrow.`,
  `Quiet day. Show up. Even messy. Especially messy.`,
  `Empty 24. Tomorrow's a new line. Write it cleanly.`,
];

/* ────────────────────────────────────────────────────────────── *
 * BEHAVIORAL — NO LOG IN 72 HOURS
 * Stronger concern / direct re-engagement.
 * ────────────────────────────────────────────────────────────── */

export const BEHAVIORAL_72H_VARIANTS: string[] = [
  `Three days. What's really going on?`,
  `Haven't heard from you in a minute. Talk to me.`,
  `You disappeared for a few days. Everything okay?`,
  `Three days off track usually means something deeper is happening.`,
  `Be honest — what pulled you away?`,
  `Not judging you. Just checking in.`,
  `Three days turns into a week faster than people think.`,
  `Talk to me. What's been going on mentally?`,
  `You've been quiet. I noticed.`,
  `Three days without a check-in. Let's reset this.`,
  `Usually when people disappear, life started feeling heavy.`,
  `Don't stay disconnected too long.`,
  `Three days away from your routine can shift a lot.`,
  `You don't have to figure it all out before coming back.`,
  `Something threw you off this week?`,
  `We getting back on track or what?`,
  `Three days gone. I'm more concerned about your mindset than perfection.`,
  `You don't need a perfect restart to begin again.`,
  `Be real with yourself: what's stopping you right now?`,
  `Sometimes avoidance feels easier than accountability.`,
  `Three days can become thirty if you let it.`,
  `You still in this?`,
  `Talk to me honestly. What changed?`,
  `A setback doesn't need to become an exit.`,
  `Don't isolate yourself from the process.`,
  `Life got heavy these last few days?`,
  `Three days missing usually means motivation isn't the real issue.`,
  `We all fall off sometimes. Coming back matters more.`,
  `You've been gone long enough to notice.`,
  `No judgment. Just honesty.`,
  `Three days later and I'm still waiting on you.`,
  `Most people quit quietly. Don't do that.`,
  `What's been harder lately — discipline or life itself?`,
  `Come back before the gap gets bigger.`,
  `Three days off routine can mess with your momentum quick.`,
  `Be honest with yourself before this stretches longer.`,
  `What's actually been keeping you away?`,
  `You don't have to disappear because things got difficult.`,
  `Three days without hearing from you feels unlike you.`,
  `Just checking if you still care about this goal the same way.`,
  `You don't need to feel ready to restart.`,
  `Three days gone. Let's stop the slide now.`,
  `Momentum fades quietly when people disconnect too long.`,
  `You've bounced back before. Do it again.`,
  `Something emotional pull you away this week?`,
  `Three days isn't failure. Staying away longer might become one.`,
  `I'd rather see an imperfect comeback than silence.`,
  `You still capable of turning this around.`,
  `Sometimes the hardest part is simply coming back after slipping.`,
  `Three days. Let's talk honestly before it becomes a pattern.`,
  `Three days. Don't let the silence stretch into a week.`,
  `72 hours. Talk to me before this becomes a pattern.`,
  `Three days quiet. The work doesn't shame you — but it's still waiting.`,
  `Three days. Honest answer: what part of life pulled you off this week?`,
  `72 hours off. Show up tomorrow. Even if it's messy. Especially if it's messy.`,
  `Three days. The version of you who finishes is the one I'm still waiting on.`,
  `72 hours. Don't avoid the log because today's the day to come back.`,
  `Three days quiet. The discipline is the return.`,
  `72 hours. What's the smallest step that's actually true tomorrow?`,
  `Three days. The path back is one breakfast log.`,
  `72 hours off. The body still needs the work. So do you.`,
  `Three days. Stop punishing yourself with stories. Just log one thing.`,
  `72 hours. Are you hiding from the food or hiding from yourself?`,
  `Three days. Don't let one slip become a full stop.`,
  `72 hours quiet. The work is patient. So am I.`,
  `Three days. The hardest part isn't perfect. It's coming back.`,
  `72 hours. Don't carry the missed days into a missed month.`,
  `Three days off. The next move is small. Pick it.`,
  `72 hours. Real talk: what would unlock tomorrow?`,
  `Three days. The longer you wait, the louder the resistance gets.`,
  `72 hours. We adjust. We don't quit. Tell me what needs adjusting.`,
  `Three days quiet. Stop. Breathe. Tomorrow we restart.`,
  `72 hours off the log. The day after a missed stretch is the most important day of the journey.`,
  `Three days. The body learns who you are by what you do most. Be the woman you said you'd be.`,
  `72 hours. Pick the smallest next step. Just one.`,
  `Three days. Don't let resistance write the next chapter.`,
  `72 hours off. We rebuild from any point. Pick a point.`,
  `Three days quiet. What's the truth?`,
  `72 hours. The shame of returning is worse than the act of returning. The act is easier.`,
  `Three days. Talk to me. One sentence. Whatever you've got.`,
  `72 hours. Be gentle. Then be honest. Then come back.`,
  `Three days. Don't bury this. Bring it into the light. Log tomorrow.`,
  `72 hours off. Want me to make tomorrow easy? Three meals. Three logs. Done.`,
  `Three days. The streak doesn't matter. The return does.`,
  `72 hours. The work asks for presence, not perfection. Be present tomorrow.`,
  `Three days quiet. The version of you doing this isn't the one quitting.`,
  `72 hours. The path forward starts where you are. Not where you wish you were.`,
  `Three days. Don't tell yourself a story about this stretch. Just show up tomorrow.`,
  `72 hours off. The body keeps the score. Make it a clean one tomorrow.`,
  `Three days. Whatever this week became, tomorrow's still yours.`,
  `72 hours. Real talk: tired or done?`,
  `Three days quiet. Honest check: what's been louder than the goal this week?`,
  `72 hours. The day after a missed stretch defines the next month. Show up.`,
  `Three days. The journey is long. Pick it back up.`,
  `72 hours. Come back when you're ready. Just don't stay gone.`,
  `Three days. The hard part is starting again. Start.`,
  `72 hours off. Stop hiding. Tomorrow we log breakfast. That's the whole ask.`,
  `Three days. The momentum waits for the return. Make it.`,
  `72 hours. Be honest with yourself first. Then with me.`,
  `Three days. Don't make this a story. Just make this a stumble.`,
];

/* ────────────────────────────────────────────────────────────── *
 * PROGRESS — 3-DAY LOGGING STREAK
 * Fires the morning after she completes 3 consecutive days with a log.
 * Banks are smaller (~30) than rhythm/behavioral because streaks fire
 * far less often — most clients hit a 3-day streak only a handful of
 * times per year (when starting or rebuilding after a slip).
 * ────────────────────────────────────────────────────────────── */

export const PROGRESS_STREAK_3_VARIANTS: string[] = [
  `3 days of logging in a row. That's the foundation.`,
  `Three days, three logs. You're tracking.`,
  `3 straight days you logged. Most people don't.`,
  `Three days logged consecutively. That's the work.`,
  `3 logs, 3 days. Don't break the chain.`,
  `You logged three days straight. Lock it in.`,
  `3-day logging streak. That's the discipline.`,
  `Three days in a row, every meal tracked. Keep going.`,
  `3 days of logging. The data's stacking up.`,
  `You showed up and logged for three straight days.`,
  `3 logs in 3 days. You're building the habit.`,
  `Three days of logging. The first hurdle's behind you.`,
  `3-day log streak. Push for five.`,
  `You logged every day for three days. That's not nothing.`,
  `3 days logged in a row. The tracking is the work.`,
  `Three days, three days of logs. You're proving you can do this.`,
  `3 days of consistent logging. Build a fourth tomorrow.`,
  `Three days, every meal logged. That's how data builds.`,
  `3-day logging streak. Don't let the fourth slip.`,
  `You logged three days straight. Real talk: that's hard.`,
  `Three days of logs. Stack another tomorrow.`,
  `3 days of showing up and logging. Lock it in.`,
  `Three straight days of meal logs. Average people don't make it past one.`,
  `3 days logged. The discipline lives in the tracking.`,
  `You logged three days in a row. Make it five.`,
  `3 consecutive days of logging. The accountability starts here.`,
  `Three days, every meal tracked. Don't drop it now.`,
  `3-day log streak. The tracking is doing its job.`,
  `You showed up and logged three days straight. Stay sharp.`,
  `Three days of logs in the books. Build on it.`,
];

/* ────────────────────────────────────────────────────────────── *
 * PROGRESS — 5-DAY LOGGING STREAK
 * Fires the morning after she completes 5 consecutive days with a log.
 * Won't fire if a 7-day milestone is also crossed — the engine picks
 * the highest applicable threshold so she gets one big celebration,
 * not three stacked pings.
 * ────────────────────────────────────────────────────────────── */

export const PROGRESS_STREAK_5_VARIANTS: string[] = [
  `5 days of logging in a row. Most diets die at day 4.`,
  `Five days of logs. You're building the engine.`,
  `5-day log streak. Two more makes a full week.`,
  `You've logged every day for five straight days.`,
  `Five days, every meal tracked. That's accountability.`,
  `5 days of logging. The data's getting honest.`,
  `Five days in a row, every log in. That's the work.`,
  `5 days, 5 days of logs. Don't break it now.`,
  `Five straight days of logging. Lock it in.`,
  `5-day log streak. The hardest part's behind you.`,
  `You logged five days in a row. The rhythm's real.`,
  `Five days of consistent meal logs. Push to seven.`,
  `5 days of tracking. Most women never get here.`,
  `Five days logged straight. Don't blow it on the weekend.`,
  `5-day log streak. The discipline is showing up daily.`,
  `You showed up and logged for five days. That's earned.`,
  `Five days, every meal in. The data tells the truth.`,
  `5 days of logging. Two more would be a full week.`,
  `Five straight days. The tracking discipline is locked.`,
  `5 days, 5 days of honest logs. Keep going.`,
  `Five days of logs. The week's right there.`,
  `5-day log streak. Don't disappear at day 6.`,
  `You logged every day for five days. That's not luck.`,
  `Five days in a row of tracking. Real talk: this is rare.`,
  `5 days of meal logs. Stack the sixth tomorrow.`,
  `Five days of showing up. Don't let the weekend break it.`,
  `5-day log streak. The tracking is the win.`,
  `You logged five days straight. Make this the new floor.`,
  `Five days of logs. Two more and it's a full week locked.`,
  `5 days, every meal tracked. Earn the seventh.`,
];

/* ────────────────────────────────────────────────────────────── *
 * PROGRESS — 7-DAY LOGGING STREAK
 * Fires the morning after she completes 7 consecutive days with a log.
 * The big one — a full week of consistency. Most apps' clients never
 * see this; the celebration should land accordingly.
 * ────────────────────────────────────────────────────────────── */

export const PROGRESS_STREAK_7_VARIANTS: string[] = [
  `7 days of logging in a row. A full week of tracking. That's rare.`,
  `Seven straight days of meal logs. Most women never get here.`,
  `7-day log streak. A full week of showing up and tracking.`,
  `You logged every meal for seven days straight.`,
  `Seven days of consistent logging. The tracking is the work.`,
  `7 days, 7 days of logs in. Lock it in.`,
  `A full week of logging. Don't let the streak die now.`,
  `Seven straight days, every meal tracked. Real talk: this is the bar.`,
  `7-day log streak. Build the next one.`,
  `You showed up and logged for a full week. Earned.`,
  `Seven days of meal logs. The discipline's locked in the tracking.`,
  `7 days of logging straight. Stack another seven.`,
  `A full week of every-meal-tracked. That's the standard now.`,
  `Seven days in a row of logs. The accountability is doing its job.`,
  `7 days logged. Two weeks in a row would be elite.`,
  `Seven days, every meal in. Don't drop it now.`,
  `7-day log streak. The tracking discipline is real.`,
  `You logged for seven days straight. That changes things.`,
  `Seven days of consistent logs. Build week two.`,
  `7 days of logging. The data's telling a story now.`,
  `A full week of meal logs. You earned this one.`,
  `Seven straight days of logging. Lock it in.`,
  `7 days, every meal tracked. The first week's the hardest.`,
  `Seven days in a row. Don't let day 8 be the one that breaks it.`,
  `7-day log streak. Keep the tracking going — that's where it stays real.`,
  `You logged for a full week. Make the next week the same.`,
  `Seven days of logs. The tracking discipline is locked.`,
  `7 days, full week, every meal in. Different woman than the one who started logging.`,
  `Seven straight days of meal logs. Two weeks would be next-level.`,
  `A full week of logging. The work was the show-up. You did it.`,
];

/* ────────────────────────────────────────────────────────────── *
 * PROGRESS — 14-DAY LOG STREAK
 * Two full weeks. The wall most women hit.
 * ────────────────────────────────────────────────────────────── */

export const PROGRESS_STREAK_14_VARIANTS: string[] = [
  `Two full weeks of logs in a row. The "two-week wall" most women hit? You walked through it.`,
  `14 days of logging straight. The data set is real now — patterns are showing.`,
  `Two weeks of meal logs without a miss. That's when the work starts compounding.`,
  `14 days. A whole pay period of tracking. The discipline's becoming who you are.`,
  `Two solid weeks of every-meal-logged. Most people quit before they get here.`,
  `14-day log streak. Real talk: this is when most quit. You didn't.`,
  `Two weeks of tracking. The first one was effort. The second one was conviction.`,
  `14 days, every meal in. Stack another two weeks — that's a month.`,
  `Two weeks of logs. The body's getting honest data for the first time, maybe ever.`,
  `14 days in a row of logging. Don't let this week be the one that breaks it.`,
  `Two full weeks of meal logs. That's the work, that right there.`,
  `14 days locked in. The next milestone is 30. Most never see it.`,
  `Two weeks of tracking without missing. The habit's wired now.`,
  `14 days of logs. The shape of your day-to-day is finally clear.`,
  `Two weeks straight. The data tells the truth — and you've been telling it.`,
  `14-day log streak. The "I'll start Monday" loop just got broken for good.`,
  `Two weeks of every-meal-tracked. Tighten one thing this week — protein, water, steps. Pick one.`,
  `14 days of logging. The pattern's not luck anymore. It's identity.`,
  `Two solid weeks. The accountability's been with you, even on the hard days.`,
  `14 days, no breaks. Lock it in.`,
];

/* ────────────────────────────────────────────────────────────── *
 * PROGRESS — 30-DAY LOG STREAK
 * A full month. Identity-level change.
 * ────────────────────────────────────────────────────────────── */

export const PROGRESS_STREAK_30_VARIANTS: string[] = [
  `30 days of logging in a row. A full month of tracking. That changes who you are.`,
  `One month of meal logs. Look at the data — that's a month of your real life on the page.`,
  `30 days. A whole month without missing. Most never see this number.`,
  `Thirty straight days of logging. The discipline's not a phase anymore.`,
  `One full month of every-meal-tracked. Different woman than the one who started.`,
  `30-day log streak. Real talk: this is the bar most coaches never get their clients to.`,
  `A month of logs. The body's working with honest data now — that's why the changes are real.`,
  `30 days, every meal in. You logged through PMS, through bad days, through the days you wanted to quit. That's the work.`,
  `Thirty days locked in. The pattern is identity now.`,
  `30 days of tracking. Two weeks felt hard. A month feels normal. That's the shift.`,
  `One month of consistent logging. The accountability is doing its job in the background now.`,
  `30 days. A full calendar month. That's the work nobody sees.`,
  `Thirty straight days of meal logs. The next milestone is 60. Fewer than 1 in 10 get there.`,
  `30 days, no breaks. Lock it in. The next one is just stacking another month.`,
  `A month of logs in a row. The "I always quit by week 2" story isn't yours anymore.`,
];

/* ────────────────────────────────────────────────────────────── *
 * PROGRESS — 60-DAY LOG STREAK
 * Two months. The bar.
 * ────────────────────────────────────────────────────────────── */

export const PROGRESS_STREAK_60_VARIANTS: string[] = [
  `60 days of logging without a miss. Two months. That's the bar.`,
  `Two months of consistent tracking. The body's been getting honest data for nine weeks straight.`,
  `60-day log streak. Most women never see this number — and most coaches never get their clients here.`,
  `Two months, every meal in. The discipline isn't even discipline anymore. It's just how you live.`,
  `60 straight days of logs. The data's a body of work now.`,
  `Two months of tracking. You logged through a holiday, through a hard week, through the day you didn't want to.`,
  `60 days. That's the kind of streak that actually changes scale weight in a meaningful way.`,
  `Two solid months of every-meal-tracked. Real talk: this is elite.`,
  `60 days of logs in a row. The next milestone is 90 — a full quarter.`,
  `Two months, no breaks. Don't let your guard down now — finish the quarter.`,
];

/* ────────────────────────────────────────────────────────────── *
 * PROGRESS — 90-DAY LOG STREAK
 * Three months. A full quarter. Near-elite.
 * ────────────────────────────────────────────────────────────── */

export const PROGRESS_STREAK_90_VARIANTS: string[] = [
  `90 days of logging in a row. A full quarter. That's the work that compounds for the rest of your life.`,
  `Three months of every-meal-tracked. The body you have now is different from the one that started.`,
  `90-day log streak. Three months without missing a day. Real talk: almost nobody does this.`,
  `A full quarter of consistent logging. The data tells the whole story now.`,
  `90 days straight. The relationship with food, with tracking, with your own honesty — different.`,
  `Three months of logs in a row. The pattern is locked into your week, your month, your life.`,
  `90 days, no breaks. That's the bar most fitness coaches don't believe is possible.`,
  `Three months of meal logs. You're a different woman than the one who took the quiz.`,
  `90 days of tracking. The next year is just stacking quarters.`,
  `A full quarter of every-meal-logged. Don't let the foot off the gas — this is when most slip.`,
];
